source 'https://rubygems.org'

gem 'schreihals', '~> 0.0.2'

# we need to override data_mapper for the time being.
gem 'document_mapper',
  :git => 'git://github.com/hmans/document_mapper.git',
  :branch => "after_load_hook"
