source 'https://rubygems.org'

group :development do
  gem 'shotgun', '~> 0.9.0'
  gem 'heroku', '~> 2.20.0'
end

group :production do
  gem 'unicorn', '~> 4.2.0'
  gem 'rack-cache', '~> 1.1.0'
end

gem 'schnitzelpress', '~> 0.1.0'
